### ISSUE TITLE
Memory leaks (Performance)

### ISSUE THREAD

**Issue by BumbleFlash** [CUTR-at-USF/MUSER#1]
**Shuttle version:**
 
 v2.0.13-beta1
 
**Device, OS:**
 
Google Pixel 3a (Android 10)

**Description of bug:**
 
Too many activity leaks in the app. Literally every activity in the app is leaking and this is not good for an app that runs in the background.  

**Steps to reproduce:**
 
 When you open the app, you'll see the "LeakCanary" library freezing the app and dumping into the memory. The message usually is "Dumping Memory. App Freezes. Brrrr. " There are also notifications that tell you what activities are leaked.

**Comment by barbeau** [comment]
To my knowledge we haven't seen any adverse impacts of this in releases after removing LeakCanary, so I'm going to close it. We can re-open if needed.
