### ISSUE TITLE
Add contentDescriptions to main controls

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/MUSER#121]
**Is your feature request related to a problem? Please describe.**
Offshoot of https://github.com/CUTR-at-USF/MUSER/issues/56 - review and add contentDescription to main app controls if it doesn't currently exist.

**Describe the solution you'd like**
Offshoot of https://github.com/CUTR-at-USF/MUSER/issues/56 - review and add contentDescription to main app controls if it doesn't currently exist.

**Comment by BumbleFlash** [comment]
@barbeau Looks like content descriptions have been implemented in all the important views in the app. I don't think there are any additional ones that are left to be added.

**Comment by barbeau** [comment]
@BumbleFlash Great, thanks!
