### ISSUE TITLE
Validate email address on start 

### ISSUE THREAD

**Issue by m-y-u** [CUTR-at-USF/MUSER#138]
**Feature:**
We need to validate/confirm the email address entered by the user.

**Solution:**
Create a new text box underneath the existing text box to validate the entered email address. 
Please reference this feature from: [onebusway-android
](https://github.com/CUTR-at-USF/onebusaway-android/commit/28df22b0c0f9407c2279f4bde2f3d06b017188fe)

**Comment by barbeau** [comment]
Closing - this is already implemented in the released version of the app
