### ISSUE TITLE
Change Last.fm API key

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/MUSER#15]
**Is your feature request related to a problem? Please describe.**
Last.fm API key is defined in `public.properties`. We should change it to our own if we use Last.fm features.

**Describe the solution you'd like**
Changes the Last.fm API key. Possibly move it to it's own unversioned file so it's not publicly exposed - see https://github.com/googlemaps/android-maps-utils/pull/706 for an example implementation in `secure.properties`.

**Describe alternatives you've considered**
Remove key from repo if we don't use Last.fm features.

**Comment by BumbleFlash** [comment]
That's a great idea. Unversioning the file with key sounds like an appropriate task to do if we're to use Last.fm features.

**Comment by barbeau** [comment]
Hongdao will sign up for API key and share via password manager.
