### ISSUE TITLE
Remove LeakCanary before release

### ISSUE THREAD

**Issue by BumbleFlash** [CUTR-at-USF/MUSER#19]
**Is your feature request related to a problem? Please describe.**
LeakCanary is pushing notifications about memory leaks and it's constantly freezing the app while dumping into memory. It should be removed from the app so that we don't confuse users with unnecessary information. 

**Describe the solution you'd like**
Remove the library and its implementation from the code.

**Describe alternatives you've considered**
Abstract its service from the user. Log any memory issues instead of pushing notifications.

**Comment by BumbleFlash** [comment]
Also, I found another method where we can build a No-Op version of LeakCanary. Please check out this [Stackoverflow forum](https://stackoverflow.com/questions/43310444/should-i-remove-leak-canary-code-classes-for-release-build) for more information.

**Comment by BumbleFlash** [comment]
Correction: The No-Op version is already implemented in the gradle file of the dev Branch.

**Comment by barbeau** [comment]
I'm assuming the no-op implementation is for release builds, and the one that logs issues is only on debug builds. But for our purposes, we can remove it entirely.

**Comment by BumbleFlash** [comment]
Great. I have opened a pull request that comments out all the LeakCanary codes.

**Comment by barbeau** [comment]
Closed by https://github.com/CUTR-at-USF/MUSER/pull/21
