### ISSUE TITLE
Add app logo for launcher icon

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/MUSER#27]
**Is your feature request related to a problem? Please describe.**
Currently the launcher icon for this project is still the Shuttle icon - we need to change this before uploading to Google Play to avoid any trademark issues and being flagged by Google Play.

**Describe the solution you'd like**
Let's use this as a logo for now:
https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.clipart=music_note&foreground.space.trim=1&foreground.space.pad=0.25&foreColor=rgba(96%2C%20125%2C%20139%2C%200)&backColor=rgb(68%2C%20138%2C%20255)&crop=0&backgroundShape=square&effects=shadow&name=ic_launcher

You can download using button in upper-right corner.

**Describe alternatives you've considered**
Welcome to ideas

**Comment by BumbleFlash** [comment]
There's also a vector asset of the legacy Shuttle logo. I tried converting our new png to svg and importing as a vector asset but the logo in the svg was messed up. Should I just remove the vector assets for now?

**Comment by barbeau** [comment]
@BumbleFlash I would expect you can just overwrite the existing `mipmap-*/ic_launcher.png` icons (and delete the existing `ic_launcher_round.png` icons) and that's it. Am I missing where launcher vector icons are currently used in the project somewhere?

**Comment by BumbleFlash** [comment]
There's an additional folder `mipmap-anydpi-v26` that has the vector assets for the logo. I guess that is interfering with the rest of mipmap and the new logo doesn't show up.

**Comment by barbeau** [comment]
Ok - just delete that for now too
