### ISSUE TITLE
Paid variant installs the free version

### ISSUE THREAD

**Issue by BumbleFlash** [CUTR-at-USF/MUSER#28]
**Describe the bug**
The paid variant of the app seems to install the free version. 

**To Reproduce**
1. In the terminal, go to the root folder
2. Type `gradlew assemblePaidRelease`
3. If you're using the emulator, then drag and drop the `app/build/ouputs/piad/app-paid-release.apk` file. Or else,
 run the command `adb install app/build/ouputs/piad/app-paid-release.apk` after connecting your phone. 
4. Open the menu on the left and go the support. 
5. The app name is displayed as Muser 1.0.0 (Free)

**Expected behavior**
The paid variant should install the paid version that unlocks all features

**Observed behavior**
The paid variant installs the free version that asks the user to Upgrade

**Device and Android version:** 

Google Pixel 3 emulator. Android 10. Stock.  Google Play services version 20.04.14

**Comment by barbeau** [comment]
@BumbleFlash Thanks! In the "Steps to repro" section, could you add the exact gradle command you're using to build, as well as the exact file name you're looking at?

**Comment by BumbleFlash** [comment]
The shuttle uses `isUpgraded` property to handle the switch between the free and paid version. In the file `BaseActivity.java`, line no 26, shuttle uses the three functions `onPurchasesUpdated`, `onPremiumPurchaseCompleted` and `onPremiumPurchaseRestored` to set the `isUpgraded` property to `true.`

     @Override
    public void onPurchasesUpdated(List<Purchase> purchases) {
        for (Purchase purchase : purchases) {
            if (purchase.getSku().equals(Config.SKU_PREMIUM)) {
                ((ShuttleApplication) getApplicationContext()).setIsUpgraded(true);
            }
        }
    }

    @Override
    public void onPremiumPurchaseCompleted() {
        ((ShuttleApplication) getApplicationContext()).setIsUpgraded(true);
        new UpgradeDialog().show(getSupportFragmentManager());
    }

    @Override
    public void onPremiumPurchaseRestored() {
        ((ShuttleApplication) getApplicationContext()).setIsUpgraded(true);
        Toast.makeText(BaseActivity.this, R.string.iab_purchase_restored, Toast.LENGTH_SHORT).show();
    }

I'm guessing the `isUpgraded` is still false as the purchase isn't made and that's why the free version is installed.

**Comment by barbeau** [comment]
I believe if you hard-code `ShuttleApplication.isUpgraded` to true and comment out any methods that modify that variable it should work.

**Comment by BumbleFlash** [comment]
Yes. You're right. I'll open a PR for this.
