### ISSUE TITLE
Make the support message relevant to Muser

### ISSUE THREAD

**Issue by BumbleFlash** [CUTR-at-USF/MUSER#34]
**Describe the bug**
The support page of the app still has traces of Shuttle. Also, we need to make sure that there's information written about Muser in other languages too. 

**To Reproduce**
1. Open the app
2. Tap the Menu button and Click Support

**Expected behavior**
Should have information related to the Muser application and the support page should redirect to our Muser support page. 

**Observed behavior**
The support page button redirects the app to the Shuttle's support page.

**Device and Android version:** 

Google Pixel 3a. Stock Android 10. Google Play Services 20.18.17

**Comment by barbeau** [comment]
Per today:
* Hide FAQ
* Hide Changelog
* Leave "Say Thanks" (but update to "MUSER" text instead of "Shuttle")
* Change "Get Help" to "Email us" which opens SEND intent with MUSER email address
