### ISSUE TITLE
Change .github/CONTRIBUTING.md

### ISSUE THREAD

**Issue by BumbleFlash** [CUTR-at-USF/MUSER#36]
**Is your feature request related to a problem? Please describe.**
The `.github/CONTRIBUTING.md` file is not relevant to MUSER. The file still has information related to Shuttle. 

**Describe the solution you'd like**
Add information related to the research work and update the developer and contact information, making it more relevant to Muser. 

**Describe alternatives you've considered**
Remove the file entirely.

**Comment by barbeau** [comment]
For a temporary fix we're going to delete the existing contributing page, and will revisit fleshing one out for MUSER later.
