### ISSUE TITLE
Add new MUSER icon

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/MUSER#42]
**Is your feature request related to a problem? Please describe.**
The existing MUSER icon was a placeholder - we should replace it with an actual icon, and preferrably using [Android adaptive icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive):
* Article - https://medium.com/google-design/designing-adaptive-icons-515af294c783
* Design specs - https://material.io/design/platform-guidance/android-icons.html#specs

**Describe the solution you'd like**
Here are two mockups for Android's Adaptive icons, one that uses a blue background with a record player in the foreground, and one that uses the record as the foreground and the player as the background:

![Screen Shot 2020-08-03 at 7 54 23 PM (2)](https://user-images.githubusercontent.com/928045/89665188-47438700-d8a6-11ea-8d0e-15b23556fcb6.png)

![Screen Shot 2020-08-03 at 7 38 22 PM (2)](https://user-images.githubusercontent.com/928045/89665202-4a3e7780-d8a6-11ea-9fd4-2757921bd56a.png)

Per discussions we prefer the 2nd with the record player as the foreground. We'll get assets for this and load them up.

**Describe alternatives you've considered**
Don't use adaptive icons

**Comment by barbeau** [comment]
Here's the latest SVG for the adaptive icon (GitHub doesn't support attaching SVGs directly, so it's zipped):

[adaptive-icon2.zip](https://github.com/CUTR-at-USF/MUSER/files/5109356/adaptive-icon2.zip)

**Comment by barbeau** [comment]
Separate foreground and background for adaptive icon:

[foreground-background.zip](https://github.com/CUTR-at-USF/MUSER/files/5110469/foreground-background.zip)

**Comment by barbeau** [comment]
I’m running into an issue when using the Android Studio "New->Image Asset" wizard to add the foreground layer. I get the message that the “foreground image may not be complete due to encountered issues”, and when I click on details I get the below message.

So it looks like line 23 `<image>` tag isn’t supported by Android Studio.

I’ll continue to try and troubleshoot. See the warnings too – looks like these aren’t fatal but I’m not sure how they would impact the final image yet.

![image](https://user-images.githubusercontent.com/928045/91460094-6b670800-e855-11ea-9f20-b0f6aa94c1c3.png)

**Comment by barbeau** [comment]
line 23 `<image>` tag appears to be the highlights on the record.

**Comment by BumbleFlash** [comment]
I have used the below tool before to generate vector assets and it did seem to be compatible with Android studio. However, it looks like it has been deprecated. Since Shuttle's codebase is pretty outdated I think this tool may help us get rid of this issue. Let me know if you found this useful. 

http://inloop.github.io/svg2android/

**Comment by barbeau** [comment]
Here's the output of that tool for the foreground image:

```
Warning #1: | found attribute 'fill-rule:evenodd' which is supported only on Android API 24 and higher - ([more info](https://github.com/inloop/svg2android/issues/44))
Warning #2: | found fill(s) or stroke(s) which uses url() (gradients and patterns are not supported in Android)
Warning #3: | image element is not supported, you must vectorize raster image
Warning #4: | transforms on path are not supported, use option Bake transforms into path
```

So unfortunately seems like it has the same issue with Warning 3, and the output looks broken look when I load the XML file into Android Studio and preview it:

![image](https://user-images.githubusercontent.com/928045/91474203-e9cca580-e867-11ea-8f25-2c55059e3ea9.png)

I get the error in Android Studio when running the wizard before even completing it and generating the icons, so it doesn't seem that the issue is with the Shuttle codebase, but with the Android raster/vector conversion utilities (i.e., what the above tool tells you to use) just not supporting certain SVG features.
