### ISSUE TITLE
Configure Firebase security for production

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/MUSER#45]
**Is your feature request related to a problem? Please describe.**

We need to make sure that the Firebase Firestore database is configured properly for security reasons for production use.

Here's the config we should use under the `Rules` tab, which only allows the user with the same ID to read and write their own data:

```
service cloud.firestore {
	match /databases/{database}/documents {
    match /users/{userId}/{document=**} {
        allow read: if request.auth.uid == userId;
        allow write: if request.auth.uid == userId;
      }
      match /users/{userId} {
        allow write: if request.auth.uid == userId;
      }
    }
}
```

It's possible to remove the "read" permission if we're not going to be reading any of the Firebase data, but if we want to do things like write the ISRC server-side and then retrieve it within the app we need the "read" permission for that.

I'm labeling this as a bug as it needs to be changed prior to a release that pushes user data to the server.

**Describe the solution you'd like**
Configure Firebase for production

**Describe alternatives you've considered**
N/A

**Comment by barbeau** [comment]
@BumbleFlash Looks like this is implemented now in Firebase? Can we close this issue?

**Comment by barbeau** [comment]
@BumbleFlash Just wanted to loop back on this - we've configured this, right? So we can close this issue?

**Comment by BumbleFlash** [comment]
@barbeau Yes, this has been implemented. We can close this. I'm so sorry that I didn't respond to you earlier. Notifications from this issue may have got buried with the other Github notifications.
