### ISSUE TITLE
Update theme colors

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/MUSER#47]
**Is your feature request related to a problem? Please describe.**
MUSER still has the old Shuttle theme colors. We should update them.

**Describe the solution you'd like**
Here's a color palette from the team:

* Primary - `#059BAD`
* Dark - `#007C8A`
* Accent - `#B5D7DE`

![colorThemes](https://user-images.githubusercontent.com/928045/90777226-1cefc180-e2c9-11ea-9a3b-726610f147e3.png)

**Describe alternatives you've considered**
Keep the current theme colors

**Comment by BumbleFlash** [comment]
@barbeau Thanks for opening this! Currently, Shuttle uses a dynamic feature that would allow the user to choose the Primary color of the app. You can find the feature by navigating through the settings --> Themes --> Choose Primary color. 

<img src="https://user-images.githubusercontent.com/22369029/90805416-90093000-e2e9-11ea-9d85-3e7a7d32615d.png" width="300">

Should I remove the option to choose this entirely so that it doesn't cause a conflict with our themes?

**Comment by barbeau** [comment]
I think leaving the custom controls is fine.

Looks like `color.xml` has the default colors?

```xml
    <color name="colorPrimary">#3F51B5</color>
    <color name="colorPrimaryDark">#303F9F</color>
    <color name="colorAccent">#FF4081</color>
```

So we should just be able to swap these out, and hopefully it just works 🤞

**Comment by BumbleFlash** [comment]
@barbeau To the best of my understanding, there's an if-block that chooses a random theme color, sets the theme, and stores the same using `SharedPreferences`. I'm guessing the value is updated when the user sets a custom theme from the settings. 
https://github.com/CUTR-at-USF/MUSER/blob/usf/app/src/main/java/com/simplecity/amp_library/ui/screens/main/MainActivity.java#L90

    if (Aesthetic.isFirstTime(this)) {

            ThemeUtils.Theme theme = ThemeUtils.getRandom();

            Aesthetic.get(this)
                    .activityTheme(theme.isDark ? R.style.AppTheme : R.style.AppTheme_Light)
                    .isDark(theme.isDark)
                    .colorPrimaryRes(theme.primaryColor)
                    .colorAccentRes(theme.accentColor)
                    .colorStatusBarAuto()
                    .apply();

            analyticsManager.logInitialTheme(theme);
        }

A quick fix here is to remove the above code and set the default themes, I can confirm it works 😄. However, the theme would still be modified if the user sets a custom theme from the settings.
