### ISSUE TITLE
Theme adapts to the background of Album Art

### ISSUE THREAD

**Issue by BumbleFlash** [CUTR-at-USF/MUSER#50]
**Description**
The app theme changes when according to the color of the album art. Here are a couple of screenshots that should give an insight into what's going on. 

1) The app is opened with the default theme. 
<img src = "https://user-images.githubusercontent.com/22369029/91077837-bd1e5100-e60f-11ea-8317-02c31710dbb5.png" width = "200"> 

2) Once the "Frank Sinatra's track is played, the app theme changes according to the album artwork of the song. 
<img src = "https://user-images.githubusercontent.com/22369029/91078023-05d60a00-e610-11ea-8f4d-11a4bac21633.png" width = "200">

Since the theme adapts as the user plays a track, our default theme will barely last for a minute after installation. Should we address this issue? Let me know your thoughts.

**Comment by barbeau** [comment]
I think the behavior is fine as is. Google was showcasing this color picking feature for a while in other apps.
