### ISSUE TITLE
User should be able to control the music when the app is not in focus. 

### ISSUE THREAD

**Issue by BumbleFlash** [CUTR-at-USF/MUSER#6]
**Is your feature request related to a problem? Please describe.**
The app doesn't have a way to play, pause or skip the track from the notification bar. The user should be able to control the track while the phone is locked or the user is using another app. 

**Solution**
The most optimal solution is to have an interface in the notification bar that allows the user to play, pause, and skip to the next song.

**Alternative Solution**
A virtual assistant like Facebook Messenger's 'Chat Heads" that floats on the screen while a track is being played could be a great addition.

**Comment by barbeau** [comment]
@BumbleFlash I see this when playing a song in the background on Samsung Galaxy S8+ w/ Android 9, using free version of Shuttle from Google Play:

![image](https://user-images.githubusercontent.com/928045/83889268-f03ffb00-a718-11ea-8605-15757ff10177.png)

Is that what you're looking for?

**Comment by barbeau** [comment]
I believe we can close this out - the notification music player seems to work fine.
