### ISSUE TITLE
Fix compatibility issue with Android 9, API LEVEL < 29

### ISSUE THREAD

**Issue by BumbleFlash** [CUTR-at-USF/MUSER#60]
**Describe the bug**
The text on the mini player is not readable when the dark mode is switched on. 

**To Reproduce**
1. Open Muser
2. Go to settings->Base Theme --> Select Dark
3. Play a song

**Expected behavior**
The text on the mini player should be visible and not camouflage with the dark theme. 

**Observed behavior**
The text on the mini player is almost invisible and camouflages with the dark theme. 

**Device and Android version:** 

Google Pixel. Android 9, API LEVEL 28.

**Screenshots:** 

<img src = "https://user-images.githubusercontent.com/22369029/93230495-bb930500-f745-11ea-8210-ae32aa0485b6.png" width = "300">

**Comment by barbeau** [comment]
For reference, looks like this was broken in https://github.com/CUTR-at-USF/MUSER/commit/7af583fb1f12e0a0e8a6a37a3707a9814e967901#diff-5bf536dfbe52453abd9bf65484949239 based on the PR #61.
