### ISSUE TITLE
Add dev and release process documentation to README

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/MUSER#68]
**Is your feature request related to a problem? Please describe.**
There are several build variants of the project, and it's not clear to newcomers what we actually use for development and release.

**Describe the solution you'd like**
Create development and release process documentation in the README

Adding two brief sections above "License" like the following would be sufficient:

```markdown

#### Development

We use the `devDebug` variant for development and testing

#### Release

To create a new release, run the following command on the command line:
XXXXXX

Then, upload the file xxxxxx.apk to Google Play.
```

@BumbleFlash Could open a PR with this info, since you've managed the release process so far?

**Comment by BumbleFlash** [comment]
Sounds good, Sean. I'll have this PR ready as soon as we merge `register-user` to the main branch.
