### ISSUE TITLE
Change App target API to 29

### ISSUE THREAD

**Issue by BumbleFlash** [CUTR-at-USF/MUSER#77]
**Is your feature request related to a problem? Please describe.**
With the release of Android 11, Google recommends any app that is uploaded to the Play Store should target API level 29. From November 2020, Google is mandating all the apps to target API 29. 

Message from PlayStore:

> Your app currently targets API level 28 and must target at least API level 29 to ensure it is built on the latest APIs optimized for security and performance.
From August 2020, new apps must target at least Android 10 (API level 29).
From November 2020, app updates must target Android 10 (API level 29).

**Describe the solution you'd like**
Upgrade the API level in the app level `build.gradle` to 29

**Describe alternatives you've considered**
N/A

**Comment by barbeau** [comment]
Here's the list of things we need to look at in the app when bumping `targetSdkVersion` to 29:
https://developer.android.com/distribute/best-practices/develop/target-sdk
