### ISSUE TITLE
Update release docs with testing protocol, initial keystore configuration

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/MUSER#83]
**Is your feature request related to a problem? Please describe.**
We should update the README release docs with more complete information.

**Describe the solution you'd like**
The README should contain high level information about testing protocol on releases. It should also explain how to set up the keystore initially on a machine before compiling a release build.

For an example see https://github.com/OneBusAway/onebusaway-android/blob/master/BUILD.md#release-builds

**Describe alternatives you've considered**
N/A

**Comment by BumbleFlash** [comment]
@barbeau Would you like me to create a separate `Readme` file for MUSER just like OBA or should I stick to the main one? Also, shall I use the same formatting as the one from OBA?

**Comment by barbeau** [comment]
Sure, let's go ahead and split out a separate `BUILD.MD` like OBA, and use the same formatting as OBA.
