### ISSUE TITLE
Update placeholder informed consent

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/MUSER#87]
**Is your feature request related to a problem? Please describe.**

We currently have placeholder text (intentionally) in the informed consent that users agree to when participating:
https://github.com/CUTR-at-USF/MUSER/blob/usf/app/src/main/res/raw/travel_behavior_informed_consent.html

**Describe the solution you'd like**

We should update the content to be the MUSER study informed consent when that is available, and also rename the file to `muser_informed_consent.html`.

Labeling this as "bug" as it needs to be resolved prior to shipping to real participants.

**Describe alternatives you've considered**
N/A

**Comment by barbeau** [comment]
Here's the latest draft (which still needs the IRB number);

[MUSER-InformedConsentScreen.docx](https://github.com/CUTR-at-USF/MUSER/files/5476698/MUSER-InformedConsentScreen.docx)

**Comment by BumbleFlash** [comment]
@barbeau Should we wait till we have access to the IRB number?

**Comment by barbeau** [comment]
@BumbleFlash Let's go ahead and add it now - we can patch in the IRB number later.

**Comment by barbeau** [comment]
I'm going to re-open this as a reminder to update the IRB number when we have it.

**Comment by barbeau** [comment]
See below from IRB:

>2.	There is specific disclosure language in the management plan (and copied below) that must be included in the informed consent document. Please reference the USF IRB [Informed Consent Templates](https://arc.research.usf.edu/Prod/Rooms/DisplayPages/LayoutInitial?Container=com.webridge.entity.Entity%5BOID%5BEC93D33F0BFE684E9BABF4F231A0A81F%5D%5D) for the appropriate heading and location of the disclosure.  I have copied Gina Larsen, IRB Manager, on this email in case you need any assistance regarding the informed consent disclosure.
>
>“Dr. Hongdao Meng and Dr. Sean Barbeau are the authors of the software being used in this study. Research studies like this one are done to determine whether the new software is effective. If research shows the new software is effective, Dr. Meng and Dr. Barbeau could receive a part of the profits from any sales of this software.
>
>The Institutional Review Board that reviewed this study and a committee at the University of South Florida have reviewed the possibility of financial benefit. They believe that the possible financial benefit to Dr. Meng and Dr. Barbeau is not likely to affect your safety and/or the scientific quality of the study. If you would like more information, please ask the researchers or the study coordinator.”

**Comment by barbeau** [comment]
IRB number is 000752

**Comment by barbeau** [comment]
IRB number updated in https://github.com/CUTR-at-USF/MUSER/pull/139.

So we just need to add the above text from https://github.com/CUTR-at-USF/MUSER/issues/87#issuecomment-868498694, and confirm with Dr. Meng that no further IRB text needs to change, and then we can close this issue.

**Comment by barbeau** [comment]
Here's the final informed consent text (including the above text from https://github.com/CUTR-at-USF/MUSER/issues/87#issuecomment-868498694) that needs to be in the app:
[InformedConsentScreen-Template.docx](https://github.com/CUTR-at-USF/MUSER/files/6946678/InformedConsentScreen-Template.docx)

**Comment by barbeau** [comment]
Final version with updated phone number:

[InformedConsentScreen-v2.docx](https://github.com/CUTR-at-USF/MUSER/files/7197794/InformedConsentScreen-v2.docx)
