### ISSUE TITLE
Track navigation UI events

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/MUSER#99]
**Is your feature request related to a problem? Please describe.**
There is interest in determining agitation level of participants, with potentially fast clicking through the app being an indicator of higher agitation. 

**Describe the solution you'd like**
We should track more navigation UI events (including the "back" button press) so we can reconstruct rapid tapping from the events.

List of UI events to detect:
- [ ] Back button
- [ ] Back Button in the navigation bar on the bottom or By Gesture (From Android 10) if used

**Comment by BumbleFlash** [comment]
Closing as Duplicate. #17 is tracking this.
